
version: '3.8'

services:
  app:
    build: ./app
    container_name: apache-app
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - db


  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app


  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:


volumes:
  db-data:

